db.username=paw-2025a-10
db.password=<CONFIGURAR_LOCALMENTE>
db.url=jdbc:postgresql://localhost/paw-2025a-10
mail.host=smtp.gmail.com
mail.port=587
mail.password=<CONFIGURAR_LOCALMENTE>
MAIL_SMTP_AUTH=true
MAIL_SMTP_STARTTLS_ENABLE=true
MAIL_DEBUG=true
jwtSecret.key=<CONFIGURAR_LOCALMENTE>
auth.key=<CONFIGURAR_LOCALMENTE>
