db.username=postgres
db.password=<CONFIGURAR_LOCALMENTE>
db.url=jdbc:postgresql://localhost/paw
mail.host=smtp.gmail.com
mail.port=587
mail.password=<CONFIGURAR_LOCALMENTE>
MAIL_SMTP_AUTH=true
MAIL_SMTP_STARTTLS_ENABLE=true
MAIL_DEBUG=true
auth.key=<CONFIGURAR_LOCALMENTE>
journey.events.created=Created
journey.events.attending=Attended
journey.events.no.created=No events created
journey.events.no.attending=No events attended
journey.detail.tips=Tips
report.action.delete_journey=Delete Journey
report.action.delete_event=Delete Event
report.action.delete_journey_comment=Delete Journey Comment
report.action.delete_event_comment=Delete Event Comment
report.content.deleted=Content deleted